#!/bin/bash

#adm1 - CRIAR PAYLOADS
#adm2 - ATIVAR/DESATIVAR TCP SPEED
#adm3 - ATIVAR/DESATIVAR BAD UDP
#adm4 - FAILBAN SQUID PROTECTION
#adm5 - ATIVAR/DESATIVAR FIREWALL
#adm6 - VCN

comando="$1"

#------------------------------------------------------------#

function_teste () {
IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
IP2=$(wget -qO- ipv4.icanhazip.com)
 if [[ "$IP" != "$IP2" ]]; then
IP="$IP2"
 fi
if [ ! -d /var ]; then
mkdir /var
fi
if [ ! -d /var/www ]; then
mkdir /var/www
fi
if [ ! -d /var/www/html ]; then
mkdir /var/www/html
fi
if [ ! -d /var/www/html/buscahost ]; then
mkdir /var/www/html/buscahost
fi
chmod -R 755 /var/www
val="$1"
mv /root/$val /var/www/html/buscahost/$val
echo ""
echo -e "ACESSE SUA LISTA DE PAYLOADS EM..."
echo -e "\033[1;36mhttp://$IP:81/buscahost/$val
ou
http://$IP:81/html/buscahost/$val
\033[0m"
}


function_payload () {
IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
IP2=$(wget -qO- ipv4.icanhazip.com)
 if [[ "$IP" != "$IP2" ]]; then
IP="$IP2"
 fi
if [ ! -d /var ]; then
mkdir /var
fi
if [ ! -d /var/www ]; then
mkdir /var/www
fi
if [ ! -d /var/www/html ]; then
mkdir /var/www/html
fi
if [ ! -d /var/www/html/payload ]; then
mkdir /var/www/html/payload
fi
chmod -R 755 /var/www
val="$1"
mv /root/$val /var/www/html/payload/$val
echo ""
echo -e "ACEDA A LA LISTA DE PAYLOADS EN..."
echo -e "\033[1;36mhttp://$IP:81/payload/$val
ou
http://$IP:81/html/payload/$val
\033[0m"
read -p "enter"
}


if [ "$comando" = "adm1" ]; then
echo -e "\033[1;33m1 \033[1;31m
DIGITE UM HOST PARA CRIAR AS PAYLOADS GENERICAS! \033[1;33m
2 \033[1;31m
DIGITE SEM HTTP//
DIGITE APENAS A HOST"
sleep 3s
echo -e "\033[1;33m__________________________________________\033[1;32m"
echo -e "\033[1;36mCREADOR DE PAYLOADS"
echo -e "\033[1;33m__________________________________________\033[0m"
echo -e "\033[1;31mECRIBIR HOST\033[1;33m"
read -p ": " valor1
if [ "$valor1" = "" ]; then
echo -e "\033[1;31mNo Digito Nada!!!"
exit
fi
echo -e "\033[1;31mDIGITE SU IP\033[1;33m"
read -p ": " valor2
if [ "$valor2" = "" ]; then
valor2="127.0.0.1"
fi
echo -e "\033[1;31mESCOJA EL METODO DE ENCABEZADO...\033[1;33m
1-GET                           
2-CONNECT
3-PUT                          
4-OPTIONS
5-DELETE                     
6-HEAD
7-TRACE                      
8-PROPATCH
9-PATCH"
read -p ": " valor3
case $valor3 in
1)
req="GET"
;;
2)
req="CONNECT"
;;
3)
req="PUT"
;;
4)
req="OPTIONS"
;;
5)
req="DELETE"
;;
6)
req="HEAD"
;;
7)
req="TRACE"
;;
8)
req="PROPATCH"
;;
9)
req="PATCH"
;;
*)
req="GET"
;;
esac
echo -e "\033[1;31mPOR ULTIMO, ESCOJA METODO DE INJECCION!\033[1;33m
1-realData
2-netData
3-raw"
read -p ": " valor4
case $valor4 in
1)
in="realData"
;;
2)
in="netData"
;;
3)
in="raw"
;;
*)
in="netData"
;;
esac
sed -e "s;realData;abc;g" /bin/esqueleton > /tmp/esq1
sed -e "s;netData;abc;g" /tmp/esq1 > /tmp/esq2
sed -e "s;raw;abc;g" /tmp/esq2 > /tmp/esq3
sed -e "s;abc;$in;g" /tmp/esq3 > /tmp/esq
sed -e "s;get;$req;g" /tmp/esq > /tmp/es
sed -e "s;mhost;$valor1;g" /tmp/es > /tmp/es1
sed -e "s;mip;$valor2;g" /tmp/es1 > /root/$valor1.txt
testt=$(cat /root/$valor1.txt |egrep -o $valor1)
if [ "$testt" = "" ]; then
echo -e ""
echo -e "\033[1;33mALGO\033[1;36m ERRADO!\033[0m"
rm -rf /root/$valor1.txt
rm -rf /tmp/es
rm -rf /tmp/es1
rm -rf /tmp/esq
rm -rf /tmp/esq1
rm -rf /tmp/esq2
rm -rf /tmp/esq3
sleep 5s
exit
fi
echo -e "\033[1;33mTERMINADO, ARCHIVO DE PAYLOADS CREADO\033[1;36m /root/$valor1.txt\033[0m"
if [ -e /etc/apache2/apache2.conf ]; then
echo -e "\033[1;31mFue Identificado ServidorWEB En Su Vps, Desea Disponibilizar ese Archivo Online?\033[0m"
while true; do
read -p "[s/n]: " pay
case $pay in
(s|S)
function_payload $valor1.txt
break
;;
(N|n)
break
;;
*)
echo "Selecione 1 opcion"
;;
esac
done
fi
sleep 3s
rm -rf /tmp/es
rm -rf /tmp/es1
rm -rf /tmp/esq
rm -rf /tmp/esq1
rm -rf /tmp/esq2
rm -rf /tmp/esq3
echo -e "\033[0m"
exit
fi

#------------------------------------------------------------#

#------------------------------------------------------------#

fun1 () {
	echo ""
echo -e "\033[1;36mLa configuración de red TCP ya se ha agregado en el sistema!"
	echo ""
	read -p "Desea remover las configuraciones de TCP? [s/n]: " -e -i n res
echo -e "\033[0m"
case $res in
(S|s)
resposta0="s"
;;
*)
echo -e "\033[1;36mVolviendo\033[0m"
sleep 2s
exit
;;
esac
if [[ "$resposta0" = 's' ]]; then
		grep -v "^#ADM
net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" /etc/sysctl.conf > /tmp/syscl && mv /tmp/syscl /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null
		echo ""
echo "La configuración de red TCP se ha eliminado con éxito."
		echo ""
fi
}

fun2 () {
	echo ""
echo -e "\033[1;33mEste es un script experimental. Por su cuenta y riesgo!\033[0m"
sleep 1s
echo -e "\033[1;31mEsta secuencia de comandos cambiará algunas configuraciones de red 
do sistema para reducir la latencia y mejorar la velocidad\033[0m"
	echo ""
read -p "Continuar con la instalacion? [s/n]: " -e -i n resp
case $resp in
(s|S)
resposta="s"
;;
*)
echo -e "\033[1;33Instalação cancelada por usuário!"
echo -e "\033[1;31mRetornando!\033[0m"
sleep 1.5s
exit
;;
esac
if [[ "$resposta" = 's' ]]; then
	echo ""
echo -e "\033[1;31mModificando...\033[0m"
	echo " " >> /etc/sysctl.conf
	echo "#ADM" >> /etc/sysctl.conf
echo "net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" >> /etc/sysctl.conf
echo ""
sysctl -p /etc/sysctl.conf
		echo ""
		echo "La configuración de red TCP se ha agregado con éxito."
fi
}


if [ "$comando" = "adm4" ]; then
echo -e "\033[01;33m________________________________________\033[01;37m"
echo -e "\033[1;33mEsse Script Foi Projetado Para Melhorar
A Latencia e Velocidade Do Servidor!"
echo -e "\033[01;33m________________________________________\033[01;37m"
sleep 1.5s
echo -e "
\033[1;36mAnalizando...\033[0m"
sleep 0.5s
if [[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]]
then
fun2
exit
 else
fun1
exit
fi
fi


#------------------------------------------------------------#

udpinst () { 
echo -e "\033[1;36mO \033[1;31mBADVPN...\033[0m será instalado, que e nada mais que um programa que libera portas UDP no servidor e assim permitindo serviço VOIP como ligação no WhatsApp, Skype, etc. 
\033[1;31mAGUARDE...\033[0m"
sleep 5s
echo -e "\033[1;36mInstalando, aguarde....\033[0m"
echo -e "\033[7;31m\033[7;41m"
for prog in $(seq 10);
do
echo -n "||"
sleep 0.1s
echo -n "|"
sleep 0.1s
done
echo -e "\033[0m"
cd /root/
wget https://www.dropbox.com/s/nxf5s1lffmbikwq/badvpn-udpgw && mv /root/badvpn-udpgw /bin/badvpn-udpgw
sleep 3s
echo -e "Badvpn Istalado"
chmod 777 /bin/badvpn-udpgw
touch /etc/adm/modulo/udp
exit
}

if [ "$comando" = "adm5" ]; then
udpvar=$(netstat -nlpt | egrep -o udpgw)
 if [ -e /etc/adm/modulo/udp ]; then
  if [ "$udpvar" = "" ]; then
echo -e "\033[1;36mIniciando... BADVPN\033[0m"
sleep 1s
nohup badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 &
test=$(ps x |grep badvpn |grep -v grep |awk '{print $1}')
if [ "$test" != "" ]; then
echo -e "\033[1;36mBADVPN iniciado...\033[0m"
fi
sleep 1s
exit
 else
echo -e "\033[1;36mParando serviço BADVPN...\033[0m"
sleep 1s
kill -9 $(ps x | grep badvpn | grep -v grep | grep bin | awk '{print $1'}) > /dev/null 2>&1
killall badvpn-udpgw > /dev/null 2>&1
test=$(ps x |grep badvpn |grep -v grep |awk '{print $1}')
if [ "$test" = "" ]; then
echo -e "\033[1;36mBADVPN parado...\033[0m"
fi
exit
  fi
else
udpinst
 fi
fi

#------------------------------------------------------------#

fail_2ban () {
if [ "$5" != "" ]; then
echo -e "\033[1;31mNao Ha Mais de 4 Opcoes\033[0m"
else
if [ -e $HOME/f2b ]; then
rm -rf $HOME/f2b
fi
touch $HOME/f2b
if [ "$1" = "1" ]; then
echo "1" >> $HOME/f2b
fi
if [ "$1" = "2" ]; then
echo "2" >> $HOME/f2b
fi
if [ "$1" = "3" ]; then
echo "3" >> $HOME/f2b
fi
if [ "$1" = "4" ]; then
echo "4" >> $HOME/f2b
fi
if [ "$2" = "1" ]; then
echo "1" >> $HOME/f2b
fi
if [ "$2" = "2" ]; then
echo "2" >> $HOME/f2b
fi
if [ "$2" = "3" ]; then
echo "3" >> $HOME/f2b
fi
if [ "$2" = "4" ]; then
echo "4" >> $HOME/f2b
fi
if [ "$3" = "1" ]; then
echo "1" >> $HOME/f2b
fi
if [ "$3" = "2" ]; then
echo "2" >> $HOME/f2b
fi
if [ "$3" = "3" ]; then
echo "3" >> $HOME/f2b
fi
if [ "$3" = "4" ]; then
echo "4" >> $HOME/f2b
fi
if [ "$4" = "1" ]; then
echo "1" >> $HOME/f2b
fi
if [ "$4" = "2" ]; then
echo "2" >> $HOME/f2b
fi
if [ "$4" = "3" ]; then
echo "3" >> $HOME/f2b
fi
if [ "$4" = "4" ]; then
echo "4" >> $HOME/f2b
fi
 fi
}

if [ "$comando" = "adm6" ]; then
 if [ -e /etc/adm/modulo/fail2ban ]; then
echo -e "Fail2ban Ativo!, Deseja Ver o Log?"
read -p "[1]-Ver o Log
[2]-Desinstalar" loog
case $loog in
1)
  if [ -e /etc/squid3/squid.conf ]; then
svar="squid3"
else
svar="squid"
  fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%48s%s%-20s\n' "LOG PRINCIPAL FAIL2BAN:" ; tput sgr0
cat /var/log/fail2ban.log
read -p "Enter"
exit
;;
2)
apt-get remove fail2ban
rm /etc/adm/modulo/fail2ban
read -p "Enter"
exit
;;
esac
 fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%48s%s%-20s\n' "FAILBAN PROTECTION     " ; tput sgr0
tput setaf 2 ; tput bold ; echo ""
echo "Este é o FAILBAN PROTECTION, criado unicamente para proteger seu  "
echo "Sistema ,seu objetivo é analizar os LOGS DE ACESSO e bloquear toda e"
echo "qualquer ação suspeita e com isso aumentar 70% sua segurança."
read -p "Deseja Instalar o Fail2Ban?
[S/N]: " fail2ban
case $fail2ban in
(S|s)
apt-get install fail2ban -y
cd $HOME
wget -O fail2ban https://www.dropbox.com/s/qtz4aihjnwpth7y/fail2ban-0.9.4.tar.gz?dl=0
tar -xf $HOME/fail2ban
cd $HOME/fail2ban-0.9.4
./setup.py install
echo '[INCLUDES]
before = paths-debian.conf
[DEFAULT]
ignoreip = 127.0.0.1/8
# ignorecommand = /path/to/command <ip>
ignorecommand =
bantime  = 1036800
findtime  = 3600
maxretry = 5
backend = auto
usedns = warn
logencoding = auto
enabled = false
filter = %(__name__)s
destemail = root@localhost
sender = root@localhost
mta = sendmail
protocol = tcp
chain = INPUT
port = 0:65535
fail2ban_agent = Fail2Ban/%(fail2ban_version)s
banaction = iptables-multiport
banaction_allports = iptables-allports
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
            %(mta)s-whois[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_xarf = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             xarf-login-attack[service=%(__name__)s, sender="%(sender)s", logpath=%(logpath)s, port="%(port)s"]
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"]
                %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_blocklist_de  = blocklist_de[email="%(sender)s", service=%(filter)s, apikey="%(blocklist_de_apikey)s", agent="%(fail2ban_agent)s"]
action_badips = badips.py[category="%(__name__)s", banaction="%(banaction)s", agent="%(fail2ban_agent)s"]
action_badips_report = badips[category="%(__name__)s", agent="%(fail2ban_agent)s"]
action = %(action_)s' > /etc/fail2ban/jail.local
sleep 1s
;;
*)
exit
;;
esac
while true; do
clear
echo -e "Escolha Para Quais Serviços Ira Utilizar Fail2ban!\033[1;31m
[1]-ssh, [2]-squid, [3]-dropbear, [4]-apache.\033[1;32m
escolha 1 ou quantos for
