#!/bin/bash

#adm90 - verifcador
#adm1 - CRIAR USUARIOS
#adm21 - CREAR USUARIO TEMPORAL OPENSSH
#adm22 - CREAR USUARIO TEMPORL DROPBEAR
#adm3 - REDEFINIR USUARIOS
#adm4 - ELIMINAR USUARIOS
#adm5 - INFORMACION DE LOS USUARIOS
#adm61 - MONITOREAR USUARIOS OPENSSH
#adm62 - MONITOREAR USUARIOS DROPBEAR
#adm7 - ELIMINAR USUARIOS VENCIDOS
#adm81 - CAMBEAR BANNER OPENSSH
#adm82 - CAMBEAR BANNER DROPBEAR
#--------------------------------------------------------------#

if [ "$1" = "adm1" ]; then
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;31mCreador De Usuarios"
echo -e "\033[1;32mNombre nuevo de usuario:\033[0;37m"; read -p " " name
if [ "$name" = "" ]; then
echo -e "\033[1;31mNada fue Digitado\033[0m"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ya existe\033[0m"
exit
fi
echo -e "\033[1;32mContraseña para el usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mCuantos dias usuario $name debe durar:\033[0;37m"; read -p " " daysrnf
echo -e "\033[1;32mCuantas conexiones?:\033[0;37m"; read -p " " limit
echo -e "\033[0m"
valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
datexp=$(date "+%d/%m/%Y" -d " +$daysrnf days")
useradd -M -s /bin/false $name -e $valid
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /etc/adm/usuarios/$name
echo "contraseña: $pass" >> /etc/adm/usuarios/$name
echo "limite: $limit" >> /etc/adm/usuarios/$name
echo "fecha: $valid" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario: \033[1;37m$name"
echo -e "\033[1;36mContraseñaa: \033[1;37m$pass"
echo -e "\033[1;36mLimite: \033[1;37m$limit"
echo -e "\033[1;36mValido: \033[1;37m$datexp"
echo -e "\033[1;36mCreado Con Exito \033[0m"
exit
fi

#--------------------------------------------------------------#

tmpusr () {
time="$1"
timer=$(( $time * 60 ))
timer2="'$timer's"
echo "#!/bin/bash
sleep $timer2
kill"' $(ps -u '"$2 |awk '{print"' $1'"}') 1> /dev/null 2> /dev/null
userdel --force $2
rm -rf /tmp/$2
exit" > /tmp/$2
}

tmpusr2 () {
time="$1"
timer=$(( $time * 60 ))
timer2="'$timer's"
echo "#!/bin/bash
sleep $timer2
kill=$(dropb | grep "$2" | awk '{print $2}')
kill $kill
userdel --force $2
rm -rf /tmp/$2
exit" > /tmp/$2
}

if [ "$1" = "adm21" ]; then
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;32mNombre de usuario:\033[0;37m"; read -p " " name
if [[ -z $name ]]
then
echo "Nada Fue digito"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ja existe\033[0m"
exit
fi
echo -e "\033[1;32mContraseña para o usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mTiempo de Duración Em Minutos:\033[0;37m"; read -p " " tmp
if [ "$tmp" = "" ]; then
tmp="30"
echo -e "\033[1;32mFue Definido 30 minutos!\033[0m"
sleep 2s
fi
useradd -M -s /bin/false $name
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /tmp/$name
tmpusr $tmp $name
chmod 777 /tmp/$name
touch /tmp/cmd
chmod 777 /tmp/cmd
echo "nohup /tmp/$name & >/dev/null" > /tmp/cmd
/tmp/cmd 2>/dev/null 1>/dev/null
rm -rf /tmp/cmd
touch /etc/adm/usuarios/$name
echo "senha: $pass" >> /etc/adm/usuarios/$name
echo "data: ($tmp)Minutos" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario Creado!\033[0m"
echo -e ""
echo -e "\033[1;36mUsuario: \033[0m$name"
echo -e "\033[1;36mContraseña: \033[0m$pass"
echo -e "\033[1;36mMinutos de Duración: \033[0m$tmp"
exit
fi

if [ "$1" = "adm22" ]; then
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[0;32m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;32mNombre de usuario:\033[0;37m"; read -p " " name
if [[ -z $name ]]
then
echo "Nada Fue digitado de Usuario"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ya existe\033[0m"
exit
fi
echo -e "\033[1;32mContraseña para el usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mTiempo de Duracion En Minutos:\033[0;37m"; read -p " " tmp
if [ "$tmp" = "" ]; then
tmp="30"
echo -e "\033[1;32mFue Definido 30 minutos!\033[0m"
sleep 2s
fi
useradd -M -s /bin/false $name
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /tmp/$name
tmpusr2 $tmp $name
chmod 777 /tmp/$name
touch /tmp/cmd
chmod 777 /tmp/cmd
echo "nohup /tmp/$name & >/dev/null" > /tmp/cmd
/tmp/cmd 2>/dev/null 1>/dev/null
rm -rf /tmp/cmd
touch /etc/adm/usuarios/$name
echo "senha: $pass" >> /etc/adm/usuarios/$name
echo "data: ($tmp)Minutos" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario Creado!\033[0m"
echo -e ""
echo -e "\033[1;36mUsuario: \033[0m$name"
echo -e "\033[1;36mContraseña: \033[0m$pass"
echo -e "\033[1;36mMinutos de Duración: \033[0m$tmp"
exit
fi

#--------------------------------------------------------------#

if [ "$1" = "adm3" ]; then
if [ -e /root/usr ]; then
rm -rf /root/usr
fi
touch /root/usr
s="1"
cat /etc/passwd |grep -v ovpn > /tmp/ussh
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo "$s $u" >> /root/usr
echo -e "\033[1;31m[ $s ]\033[1;33m $u \033[0m"
s=$(($s + 1))
done
echo -e "\033[1;32m----------------------------------\033[0m"
ussrs=$(($s - 1))
echo -e "\033[1;36mSelecione O Usuario, O Escriba su Nombre!\033[0m"
read -p "NOME ou [ 1 - $ussrs ]: " client
if [ "$client" = "" ]
then
echo -e "\033[1;31mNingun Usuario Fue Selecionado\033[0m"
exit
fi
if [ "$client" -le "$ussrs" ] 1> /dev/null 2> /dev/null
then
sed -n $client' p;' /root/usr | awk '{print $2}' > /etc/adm/name
clientname=$(head -n 1 /etc/adm/name)
rm -rf /etc/adm/name
rm -rf /root/usr
 else
if cat /etc/passwd |grep $client: > /dev/null
 then
clientname="$client"
rm -rf /root/usr
 else
 echo "Usuario $client No Existe"
sleep 5s
rm -rf /root/usr
 exit
 fi
fi
##
namer="$clientname"
echo -e "\033[1;36mQue desea Redefinir?"
echo -e "\033[1;33m
[ 1 ] - Numero de logins de\033[1;31m $namer \033[1;33m?
[ 2 ] - Data de expiracion de\033[1;31m $namer \033[1;33m?
[ 3 ] - cambiar contraseña de\033[1;31m $namer \033[1;33m?"
echo -e "\033[1;36m"
read -p "[1-3]: " opt
echo -e "\033[0m"

if [ "$opt" = "1" ]; then
read -p "Cual es el nuevo limite de logins: " liml
if [ "$liml" = "" ]; then
echo "Limite No Alterado!"
exit
fi
var1=$(cat /etc/adm/usuarios/$namer | grep "contraseña")
var2=$(cat /etc/adm/usuarios/$namer | grep "fecha")
echo -e "$var1
$var2
limite: $liml" > /etc/adm/usuarios/$namer
echo -e "Limite Alterado!"
exit
fi

if [ "$opt" = "2" ]; then
echo -e "\033[1;36mCuantos Dias Debe Durar?\033[0m"
read -p ": " date
if [ "$date" = "" ]; then
echo "Fecha no Alterada!"
exit
fi
datexp=$(date "+%d/%m/%Y" -d " + $date days")
valid=$(date '+%C%y-%m-%d' -d " + $date days")
chage -E $valid $namer 2> /dev/null
echo -e "Alterado!"
var1=$(cat /etc/adm/usuarios/$namer | grep -v "data")
echo -e "$var1" > /etc/adm/usuarios/$namer
echo -e "Fecha: $valid" >> /etc/adm/usuarios/$namer
echo -e "Fecha Alterada!"
echo -e "\033[1;31mUsuario: $namer
Date: $datexp\033[0m"
exit
fi

if [ "$opt" = "3" ]; then
read -p "Cual es la nueva contraseña para $namer: " senha
if [ "$senha" = "" ]; then
echo "Contraseña No Alterada!"
exit
fi
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
var1=$(cat /etc/adm/usuarios/$namer | grep -v "senha")
echo -e "$var1" > /etc/adm/usuarios/$namer
echo -e "Contraseña: $senha" >> /etc/adm/usuarios/$namer
echo "Nueva Contraseña aplicada"
exit
fi
case $opt in
*)
echo -e "No fue seleccionada ninguna opcion!"
;;
esac
fi

#--------------------------------------------------------------#

if [ "$1" = "adm4" ]; then
echo -e "\033[41;1;37mRemover Usuarios\033[0m"
echo -e "\033[1;36m
[ 1 ] - Eliminar 1 Usuario
[ 2 ] - Eliminar Todos Usuarios\033[0m"
read -p "[1-2]: " opc
case $opc in
1)
;;
2)
;;
*)
echo -e "Opcion Invalida"
exit
;;
esac
if [ "$opc" = "1" ]; then
 if [ -e /root/usr ]; then
rm -rf /root/usr
 fi
touch /root/usr
s="1"
cat /etc/passwd |grep -v ovpn > /tmp/ussh
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo "$s $u" >> /root/usr
echo -e "\033[1;31m[ $s ]\033[1;33m $u \033[0m"
s=$(($s + 1))
done
echo -e "\033[1;32m----------------------------------\033[0m"
ussrs=$(($s - 1))
echo -e "\033[1;36mSelecione O Usuario, O Escriba su nombre!\033[0m"
read -p "Nombre [ 1 - $ussrs ]: " client
 if [ "$client" = "" ]
then
echo -e "\033[1;31mNingun Usuario Fue Selecionado\033[0m"
exit
 fi
 if [ "$client" -le "$ussrs" ] 1> /dev/null 2> /dev/null
then
sed -n $client' p;' /root/usr | awk '{print $2}' > /etc/adm/name
clientname=$(head -n 1 /etc/adm/name)
rm -rf /etc/adm/name
rm -rf /root/usr
 else
 if cat /etc/passwd |grep $client: > /dev/null
then
clientname="$client"
rm -rf /root/usr
else
echo "Usuario $client No Existe"
sleep 5s
rm -rf /root/usr
 exit
  fi
 fi
#
name="$clientname"
 userdel --force $name > /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
kill=$(dropb | grep "$name" | awk '{print $2}')
if [ "$kill" != "" ]; then
kill $kill
fi
if [ -e /etc/adm/usuarios/$name ]; then
rm -rf /etc/adm/usuarios/$name
fi
echo -e "\033[1;32m-----------------------------\033[0m"
echo -e "$name Removido\033[0m"
echo -e "\033[1;32m-----------------------------\033[0m"
 exit
fi

if [ "$opc" = "2" ]; then
cat /etc/passwd |grep -v ovpn > /tmp/ussh
for name in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
userdel --force $name > /dev/null 2>&1
kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}`  > /dev/null 2>&1
kill=$(dropb | grep "$name" | awk '{print $2}')
if [ "$kill" != "" ]; then
kill $kill
fi
if [ -e /etc/adm/usuarios/$name ]; then
rm -rf /etc/adm/usuarios/$name
fi
echo -e "\033[1;32m-----------------------------\033[0m"
echo -e "\033[1;31m$name Removido\033[0m"
sleep 0.3s
done
echo -e "\033[1;32m------------------------------\033[0m"
rm -rf /tmp/ussh
 fi
fi
#--------------------------------------------------------------#

if [ "$1" = "adm5" ]; then
touch /tmp/qusers
echo -e "\033[1;30m------------------------------------------------------------\033[0m"
echo -e "\033[42;30m Usuario               Senha               Data E.          Logins\033[0m"
echo -e "\033[1;31mUSUARIOS OPENVPN/SSH \033[0m"
echo -e "\033[1;30m------------------------------------------------------------\033[0m"
for namer in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
if [ -e /etc/adm/usuarios/$namer ]; then
temporario=$(cat /etc/adm/usuarios/$namer | grep "Minutos")
fi
if [ "$temporario" != "" ]; then
limitecs="Temporário"
senha=$(cat /etc/adm/usuarios/$namer | grep "senha" | awk '{print $2}')
data="Temporário"
else
if [ -e /etc/adm/usuarios/$namer ]; th
