#!/bin/bash
source menu-txt
echo -ne "${cor[6]}"
read -p " ${txt[9]} " _selecao
case $_selecao in
0)
clear
echo -e "${cor[0]}"
exit
;;
1)
clear
source user
exit
;;
2)
clear
source ferramentas
exit
;;
3)
fun_atualizar
exit
;;
4)
remover_adm
exit
;;
5)
funcao_cores
source menu
exit
;;
6)
funcao_verificacao > /dev/null 2>&1
source menu
exit
;;
7)
funcao_idioma
source menu
exit
;;
8)
if [[ -e /etc/bash.bashrc-bakup ]]; then
mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
cat /etc/bash.bashrc | grep -v "/bin/adm" > /tmp/bash
mv -f /tmp/bash /etc/bash.bashrc
echo -e "${cor[5]} =================================== ${cor[0]}"
echo -e "${cor[2]} \033[1;32mDESISTALADO CON EXITO!"
echo -e "${cor[5]} =================================== ${cor[0]}"
elif [[ -e /etc/bash.bashrc ]]; then
cat /etc/bash.bashrc|grep -v /bin/adm > /etc/bash.bashrc.2
echo '/bin/adm' >> /etc/bash.bashrc.2
cp /etc/bash.bashrc /etc/bash.bashrc-bakup
mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} \033[1;32mAUTORUN ACTIVO"
echo -e "${cor[5]} =================================== ${cor[0]}"
fi
sleep 2s
source menu
exit
;;
9)
bash menu_instala

;;
10)
echo -e "${cor[5]} =================================== ${cor[0]}"
echo -e "${cor[2]}  suscribite
echo -e "${cor[2]}  https://www.youtube.com/channel/UCXXRtv7G43pc-yTkGQwUQNQ    "
echo -e "${cor[1]} =================================== ${cor[0]}"
sleep 3s
source menu
exit
;;
*)
source menu
;;
esac
